"""empty message

Revision ID: 6dfa9eeb2361
Revises: 8a1bf3f97b26
Create Date: 2021-07-08 14:52:05.443034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfa9eeb2361'
down_revision = '8a1bf3f97b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('potential_matches', sa.Column('declined', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('potential_matches', 'declined')
    # ### end Alembic commands ###
