"""empty message

Revision ID: f6cb38ca580b
Revises: 01c24cac20dd
Create Date: 2021-08-09 18:59:28.205277

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'f6cb38ca580b'
down_revision = '01c24cac20dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'matchId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'matchId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
