"""empty message

Revision ID: 01c24cac20dd
Revises: 6dfa9eeb2361
Create Date: 2021-08-09 17:09:40.196974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '01c24cac20dd'
down_revision = '6dfa9eeb2361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'senderUsername')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('senderUsername', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
