"""empty message

Revision ID: 30050c1d9876
Revises: 
Create Date: 2021-06-29 18:40:37.204949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30050c1d9876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=60), nullable=False),
    sa.Column('firstName', sa.String(length=60), nullable=False),
    sa.Column('lastName', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profileImage', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('useroneId', sa.Integer(), nullable=False),
    sa.Column('usertwoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['useroneId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usertwoId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('potential_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('matchedUserId', sa.Integer(), nullable=False),
    sa.Column('matchedUsername', sa.String(length=60), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['matchedUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tea', sa.String(length=20), nullable=False),
    sa.Column('sugar', sa.Integer(), nullable=False),
    sa.Column('addons', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lactose', sa.Boolean(), nullable=False),
    sa.Column('fruit', sa.Boolean(), nullable=False),
    sa.Column('searchHeight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('matchId', sa.Integer(), nullable=False),
    sa.Column('senderUsername', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['senderUsername'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('preferences')
    op.drop_table('potential_matches')
    op.drop_table('matches')
    op.drop_table('users')
    # ### end Alembic commands ###
